# Generated by Django 5.0 on 2023-12-24 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UI_Images",
        ),
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
    ]
